#!/usr/bin/env bash

finish() {
    kill $PID 2>/dev/null
}

trap finish EXIT

export test_port="8080"
./start &
PID=$!
sleep 2
./test
kill $PID 2>/dev/null

export test_port="8081"
./start env &
PID=$!
sleep 2
./test
kill $PID 2>/dev/null
