#!/usr/bin/env bash

finish() {
    kill $PID 2>/dev/null
}

trap finish EXIT

export test_port="8080"
./start opts &
PID=$!
sleep 5
./test
EX1=$?
wait $PID 2>/dev/null
echo

export test_port="8081"
./start env &
PID=$!
sleep 5
./test
EX2=$?
wait $PID 2>/dev/null
echo

export test_port="8081"
./start env_and_opts &
PID=$!
sleep 5
./test
EX3=$?
wait $PID 2>/dev/null

if [[ $EX1 -eq 0 ]] && [[ $EX2 -eq 0 ]]  && [[ $EX3 -eq 0 ]]; then
    exit 0
else
    exit -1
fi
