#!/usr/bin/env bash

test_host="127.0.0.1"
#test_port="8080"

# from https://raymii.org/s/articles/Check_servers_for_the_Poodle_bug.html

echo QUIT | openssl s_client -connect ${test_host}:${test_port} -ssl3
if [[ $? -eq 0 ]]; then
    echo "FAIL: ${test_host} vulnerable; sslv3 connection accepted"
    exit -1
else
    echo "OK: ${test_host} Not vulnerable"
fi
