#!/usr/bin/env bash

test_host="127.0.0.1"
#test_port="8080"

# from https://raymii.org/s/articles/Check_servers_for_the_Poodle_bug.html

# Check for exit code 35: SSL connect error. The SSL handshaking failed.
curl -s -3 --insecure https://${test_host}:${test_port}  -o /dev/null
if [[ $? != 35 ]]; then
    echo "FAIL: ${test_host} vulnerable; sslv3 connection accepted"
    exit -1
else
    echo "OK: ${test_host} Not vulnerable"
fi
